System.out.println("Age      | M/YY - Descrption                    ");
System.out.println("         |                                      ");
System.out.println("1        | 5/09 - first time swimming           ");
System.out.println("         |                                      ");
System.out.println("         |                                      ");
System.out.println("3        | 9/1 - preschool                      ");
System.out.println("         |                                      ");
System.out.println("         |                                      ");
System.out.println("4        | 6/12 - first time at Disney World    ");
System.out.println("         |                                      ");
System.out.println("5        | 1/13 - first day of elementary school");
System.out.println("         |                                      ");
System.out.println("         |                                      ");
System.out.println("6        | 4/14 - Started soccer                ");